<?xml version="1.0"?>
<package format="3">
  <name>massage_bringup</name>
  <version>0.1.0</version>
  <description>Launch and configuration package for the massage robot system.</description>
  <maintainer email="xieffield@todo.todo">xieffield</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>moveit_configs_utils</exec_depend>
  <exec_depend>massage_motion</exec_depend>
  <exec_depend>massage_task</exec_depend>
  <exec_depend>jaka_s5_moveit_config</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
