<?xml version="1.0"?>
<package format="3">
  <name>massage_motion</name>
  <version>0.1.0</version>
  <description>Basic motion planning types and interfaces for the massage robot project.</description>
  <maintainer email="xieffield@todo.todo">xieffield</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>geometry_msgs</depend>
  <depend>moveit_msgs</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>moveit_ros_planning_interface</depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
